DashCamTube/Controllers/CommentController.cs
using DashCamTube.Models;
using DashCamTube.ViewModels;
using System;
using System.Web.Mvc;

namespace DashCamTube.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private ApplicationDbContext _context { get; set; }


        public CommentController()
        {
            _context = new ApplicationDbContext();
        }


        //[HttpPost]
        public ActionResult AddComment(CommentViewModel commentViewModel)
        {

            if (!ModelState.IsValid)
                return RedirectToAction("SingleViewOfFootage", "Footage", new { id = commentViewModel.FootageId });
            //return PartialView("_CommentForm", commentViewModel);


            var comment = new Comment()
            {
                Content = commentViewModel.Content,
                DateTime = DateTime.Now,
                FootageId = commentViewModel.FootageId,
                UserId = commentViewModel.UserId
            };

            _context.Comments.Add(comment);
            _context.SaveChanges();
            //return PartialView("_CommentForm", commentViewModel);

            return RedirectToAction("SingleViewOfFootage", "Footage", new { id = commentViewModel.FootageId });

            //return PartialView("_CommentForm", new CommentViewModel(commentViewModel.UserId, commentViewModel.FootageId));
        }
    }
}

DashCamTube/Controllers/HomeController.cs
using DashCamTube.Models;
using PagedList;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;


namespace DashCamTube.Controllers
{
    public class HomeController : Controller
    {

        private ApplicationDbContext _context { get; set; }

        public HomeController()
        {
            _context = new ApplicationDbContext();
        }


        //[Route("Page/{page?}")]
        public ActionResult Index(int? page)
        {
            var footages = _context.Footages
                .Include(f => f.User)
                .OrderByDescending(f => f.Time)
                .ToList().ToPagedList(page ?? 1, 10);

            return View(footages);
        }











        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return SingleViewOfFootage();
        //}

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return SingleViewOfFootage();
        //}
    }
}

DashCamTube/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DashCamTube/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DashCamTube/Views/Home/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<DashCamTube.Models.Footage>
@{
    ViewBag.Title = "Home Page";
}

@foreach (var footage in Model)
{
    <div class="post clearfix">
        <div class="postBar">
            <span class="title"><a href="@Url.Action("SingleViewOfFootage","Footage", new { id = footage.Id })">@footage.Title</a></span>
            <span class="date">@footage.User.UserName, @footage.Time.ToShortDateString()</span>
        </div>
        <div class="video">
            <iframe width="650" height="360" src="@footage.YtLink" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        @if (footage.RegistrationNumber != null)
        {
            <div class="plate"><span>@footage.RegistrationNumber</span></div>
        }      
        <span class="description">@footage.Description</span>
        
        <button class="btn btn-default btn-sm pull-right" onclick="location.href='@Url.Action("SingleViewOfFootage", "Footage", new { id = footage.Id } )'">comments</button>
        @*@Html.Action("GetCommentForm","Comment", footage)*@
    </div>
}
<div class="text-center">
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>