DashCamTube/Controllers/FootageController.cs
using DashCamTube.Models;
using DashCamTube.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace DashCamTube.Controllers
{
    public class FootageController : Controller
    {
        private ApplicationDbContext _context;

        public FootageController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        [HttpGet]
        public ActionResult AddFootage()
        {
            return View(new FootageFormViewModel());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFootage(FootageFormViewModel footageFromForm)
        {
            if (!ModelState.IsValid)
                return View(footageFromForm);

            var footage = new Footage()
            {
                UserId = User.Identity.GetUserId(),
                Title = footageFromForm.Title,
                Description = footageFromForm.Description,
                YtLink = footageFromForm.GetEmbedLink(),
                RegistrationNumber = footageFromForm.GetFromattedRegNumber(),
                Time = DateTime.Now
            };

            _context.Footages.Add(footage);
            _context.SaveChanges();


            return View(new FootageFormViewModel("You successfully added your footage!"));
        }

        //[Route("footage/{id?}")]
        public ActionResult SingleViewOfFootage(int id)
        {
            var footage = _context.Footages
                .Include(f => f.User)
                .Include(f => f.Comments)
                .SingleOrDefault(f => f.Id == id);

            if (footage == null)
                return RedirectToAction("Index", "Home");

            return View(footage);
        }

    }
}

DashCamTube/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,900&amp;subset=latin-ext" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DashCamTube", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add a video!", "AddFootage", "Footage")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>